version: '3.9'
services:
  app:
    build: .
    container_name: technical-assessment-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - redis
  redis:
    image: redis:7.2-alpine
    container_name: technical-assessment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
